name: hardened-valkey
tag: "8"
latest: false
alpine_version: "3.22"
description: Hardened Valkey 8.1 cache on Alpine 3.22

components:
  - valkey-8

expose:
  - 6379

run_as: valkey
entrypoint: ["/usr/bin/valkey-server", "/etc/valkey/valkey.conf"]

distroless: true
ipv6: false

labels:
  org.opencontainers.image.title: hardened-valkey
  org.opencontainers.image.description: Hardened Valkey 8.1 on Alpine 3.22
  org.opencontainers.image.vendor: IronVigil
  org.opencontainers.image.source: https://github.com/Iron-Vigil/forge
